# Pipeline for pushing Helm Chart to ACR
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr: none

variables:
- group: ACR SP
- name: HELM_EXPERIMENTAL_OCI
  value: 1
- name: ACR.Name
  value: 'ctcsandboxodpacr'

stages:
- stage: build
  displayName: Build and Push
  jobs:  
  - job: job_helm
    displayName: Helm Publish
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - bash: |
        helm registry login $(ACR.Name).azurecr.io --username $(acr_sp_id) --password $(acr_sp_secret)
        helm chart save . $(ACR.Name).azurecr.io/charts/hello-world:latest
        helm chart push $(ACR.Name).azurecr.io/charts/hello-world:latest